module.exports = {
    screenWidthSmall: "720px",
    screenWidthMediumSmall: "920px",
    screenWidthMedium: "1080px",
    screenWidthMediumLarge: "1280px",
    screenWidthLarge: "1420px",
    screenWidthExtraLarge: "1600px",
    menuButtonHeight: "45px",
    menuFontSize: "14pt",
    menuFontSizeSmall: "13pt",
    menuFontColor: "white",
    menuLogoSize: "70px",
    menuLogoSizeSmall: "60px",
    backgroundColor: "#222",
    secondaryBackgroundColor: "#333",
    menuSecondaryBackgroundColor: "#333",
};
